-- 002_first_run_setup.sql
-- First-run Setup Wizard support.
--
-- Adds columns to the system_settings singleton for the secure one-time setup code
-- and an explicit "first-run setup completed" marker that is independent of the
-- timezone-only initial_setup_completed flag. Idempotent and safe on existing
-- installs (all additive, IF NOT EXISTS). No data rows are created or modified here;
-- reconciliation of setup state for existing installs is handled by backend bootstrap.

ALTER TABLE public.system_settings
  ADD COLUMN IF NOT EXISTS setup_code_hash text;

ALTER TABLE public.system_settings
  ADD COLUMN IF NOT EXISTS setup_code_updated_at timestamp with time zone;

ALTER TABLE public.system_settings
  ADD COLUMN IF NOT EXISTS setup_completed_at timestamp with time zone;

ALTER TABLE public.system_settings
  ADD COLUMN IF NOT EXISTS setup_completed_by text;

COMMENT ON COLUMN public.system_settings.setup_code_hash IS
  'SHA-256 (hex) of the one-time first-run setup code generated by installation.sh. NULL once setup is completed or when no code protection is configured. Plaintext is never stored.';

COMMENT ON COLUMN public.system_settings.setup_completed_at IS
  'Timestamp the first-run Setup Wizard completed (System Administrator created + timezone selected). NULL until the wizard finishes.';

COMMENT ON COLUMN public.system_settings.setup_completed_by IS
  'Username of the System Administrator created during first-run setup (audit convenience). Never a password or secret.';

-- Existing installations that already have at least one user are, by definition, past
-- first-run: mark setup complete so the wizard never re-triggers for them and any seeded
-- setup code hash is cleared. Greenfield installs (empty users table) are untouched and
-- go through the wizard. This runs once; re-running is a no-op.
UPDATE public.system_settings AS s
   SET setup_completed_at = COALESCE(s.setup_completed_at, s.initial_setup_completed_at, NOW()),
       setup_code_hash = NULL,
       updated_at = NOW()
 WHERE s.id = 1
   AND s.setup_completed_at IS NULL
   AND EXISTS (SELECT 1 FROM public.users LIMIT 1);
