-- Sprint 1: granular import run metrics for feed health visibility.

ALTER TABLE integration_runs
  ADD COLUMN IF NOT EXISTS records_inserted INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS records_updated INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS records_duplicate INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS records_skipped INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS records_suppressed INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS records_failed INTEGER NOT NULL DEFAULT 0;

ALTER TABLE integration_queue_jobs
  ADD COLUMN IF NOT EXISTS records_inserted INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS records_updated INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS records_duplicate INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS records_skipped INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS records_suppressed INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS records_failed INTEGER NOT NULL DEFAULT 0;
