-- JSON output format + JSON include options for Published Feeds.
--
-- Extends the existing `format` column (the project's established output-format
-- convention) to allow 'json' alongside 'txt', and adds three boolean include
-- toggles that only affect JSON feeds.
--
-- Backward compatible / non-destructive:
--   * Existing rows keep format = 'txt' and behave exactly as before.
--   * No slug / key / public URL / snapshot rewrite. Existing TXT artifacts keep
--     serving until the feed is regenerated by the normal lifecycle.
--   * The include_* toggles are inert for TXT feeds; they default to the documented
--     JSON defaults (source metadata + classification on, enrichment off).

SET LOCAL statement_timeout = 0;
SET LOCAL lock_timeout = '120s';

-- Allow 'json' in addition to 'txt'. The old constraint only permitted 'txt'.
ALTER TABLE published_feeds
  DROP CONSTRAINT IF EXISTS chk_published_feeds_format;

ALTER TABLE published_feeds
  ADD CONSTRAINT chk_published_feeds_format CHECK (format IN ('txt', 'json'));

-- JSON include options. Defaults match the documented new-JSON-feed defaults and are
-- harmless for existing TXT rows (ignored by the TXT generator + serving path).
ALTER TABLE published_feeds
  ADD COLUMN IF NOT EXISTS include_source_metadata BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE published_feeds
  ADD COLUMN IF NOT EXISTS include_classification BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE published_feeds
  ADD COLUMN IF NOT EXISTS include_enrichment BOOLEAN NOT NULL DEFAULT FALSE;
