/** @typedef {'info' | 'warning' | 'critical'} AuditSeverity */
/** @typedef {'success' | 'failed'} AuditStatus */

export const AUDIT_SEVERITY = Object.freeze({
  INFO: 'info',
  WARNING: 'warning',
  CRITICAL: 'critical'
});

export const AUDIT_STATUS = Object.freeze({
  SUCCESS: 'success',
  FAILED: 'failed'
});

export const AUDIT_ACTION = Object.freeze({
  IOC_CREATED: 'ioc.created',
  IOC_DELETED: 'ioc.deleted',
  IOC_TAG_ADDED: 'ioc.tag.added',
  IOC_TAG_REMOVED: 'ioc.tag.removed',
  IOC_SUPPRESSION_CREATED: 'ioc.suppression.created',
  IOC_SUPPRESSION_UPDATED: 'ioc.suppression.updated',
  IOC_SUPPRESSION_DELETED: 'ioc.suppression.deleted',
  IOC_MATCH_EVENT_VERDICT_CHANGED: 'ioc.match_event.verdict_changed',
  INCIDENT_UPDATED: 'incident.updated',
  INCIDENT_CLOSED: 'incident.closed',
  INCIDENT_REOPENED: 'incident.reopened',
  INCIDENT_VERDICT_CHANGED: 'incident.verdict_changed',
  INCIDENT_ASSIGNED: 'incident.assigned',
  INCIDENT_AI_INSIGHT_UPDATED: 'incident.ai_insight.updated',
  ENVIRONMENT_AI_INSIGHT_REFRESH: 'environment_ai_insight.refresh',
  USER_CREATED: 'user.created',
  USER_UPDATED: 'user.updated',
  USER_DELETED: 'user.deleted',
  USER_ROLE_CHANGED: 'user.role_changed',
  USER_PASSWORD_CHANGED: 'user.password_changed',
  USER_STATUS_CHANGED: 'user.status_changed',
  API_KEY_CREATED: 'api_key.created',
  API_KEY_UPDATED: 'api_key.updated',
  API_KEY_ROTATED: 'api_key.rotated',
  API_KEY_DELETED: 'api_key.deleted',
  INTEGRATION_ENABLED: 'integration.enabled',
  INTEGRATION_DISABLED: 'integration.disabled',
  INTEGRATION_TRUST_LEVEL_CHANGED: 'integration.trust_level_changed',
  INTEGRATION_SCHEDULE_CHANGED: 'integration.schedule_changed',
  INTEGRATION_FEED_CONFIDENCE_UPDATED: 'feed.confidence_updated',
  INTEGRATION_CREDENTIALS_CHANGED: 'integration.credentials_changed',
  INTEGRATION_RUN_TRIGGERED: 'integration.run_triggered',
  INTEGRATION_QUEUE_RECOVERY: 'integration.queue_recovery',
  FEED_DATA_PURGE_PREVIEW: 'feed.data_purge.preview',
  FEED_DATA_PURGE_REQUESTED: 'feed.data_purge.requested',
  FEED_DATA_PURGED: 'feed.data_purged',
  FEED_DATA_PURGE_FAILED: 'feed.data_purge.failed',
  FEED_ARCHIVED: 'feed.archived',
  FEED_RESTORED: 'feed.restored',
  THREAT_FEED_EXPIRATION_POLICY_CREATED: 'threat_feed.expiration_policy.created',
  THREAT_FEED_EXPIRATION_POLICY_UPDATED: 'threat_feed.expiration_policy.updated',
  THREAT_FEED_EXPIRATION_POLICY_DISABLED: 'threat_feed.expiration_policy.disabled',
  IOC_FEED_MEMBERSHIP_EXPIRED: 'ioc_feed_membership.expired',
  IOC_FEED_MEMBERSHIP_REACTIVATED_BY_FEED: 'ioc_feed_membership.reactivated_by_feed',
  IOC_FEED_MEMBERSHIP_REACTIVATED_BY_MATCH: 'ioc_feed_membership.reactivated_by_match',
  IOC_FEED_MEMBERSHIP_REACTIVATED_BY_USER: 'ioc_feed_membership.reactivated_by_user',
  IOC_FEED_MEMBERSHIP_OVERRIDE_SET: 'ioc_feed_membership.override_set',
  IOC_FEED_MEMBERSHIP_OVERRIDE_CLEARED: 'ioc_feed_membership.override_cleared',
  IOC_FEED_MEMBERSHIP_EXPIRED_BY_USER: 'ioc_feed_membership.expired_by_user',
  IOC_STATUS_CHANGED: 'ioc.status.changed',
  IOC_EXPIRED: 'ioc.expired',
  IOC_REACTIVATED_BY_USER: 'ioc.reactivated_by_user',
  IOC_REACTIVATED_BY_MATCH: 'ioc.reactivated_by_match',
  IOC_OVERRIDE_SET: 'ioc.override_set',
  IOC_OVERRIDE_CLEARED: 'ioc.override_cleared',
  IOC_CONFIDENCE_OVERRIDE_SET: 'ioc.confidence.override_set',
  IOC_CONFIDENCE_OVERRIDE_CLEARED: 'ioc.confidence.override_cleared',
  FEED_CREATED: 'feed.created',
  FEED_UPDATED: 'feed.updated',
  FEED_DELETED: 'feed.deleted',
  FEED_RUN_TRIGGERED: 'feed.run_triggered',
  FEED_ACCESS_KEY_CREATED: 'feed.access_key.created',
  FEED_ACCESS_KEY_UPDATED: 'feed.access_key.updated',
  FEED_ACCESS_KEY_REVOKED: 'feed.access_key.revoked',
  TAG_CREATED: 'tag.created',
  TAG_UPDATED: 'tag.updated',
  TAG_DISABLED: 'tag.disabled',
  TAG_ENABLED: 'tag.enabled',
  THREAT_ACTOR_CREATED: 'threat_actor.created',
  THREAT_ACTOR_UPDATED: 'threat_actor.updated',
  THREAT_ACTOR_DISABLED: 'threat_actor.disabled',
  THREAT_ACTOR_ENABLED: 'threat_actor.enabled',
  THREAT_CLASSIFICATION_CREATED: 'threat_classification.created',
  THREAT_CLASSIFICATION_UPDATED: 'threat_classification.updated',
  THREAT_CLASSIFICATION_DISABLED: 'threat_classification.disabled',
  THREAT_CLASSIFICATION_ENABLED: 'threat_classification.enabled',
  IOC_THREAT_CLASSIFICATION_UPDATED: 'ioc.threat_classification.updated',
  IOC_THREAT_CLASSIFICATIONS_UPDATED: 'ioc.threat_classifications.updated',
  IOC_THREAT_ACTOR_UPDATED: 'ioc.threat_actor.updated',
  IOC_SOURCE_CREATED: 'ioc_source.created',
  IOC_SOURCE_UPDATED: 'ioc_source.updated',
  IOC_SOURCE_DISABLED: 'ioc_source.disabled',
  IOC_SOURCE_ENABLED: 'ioc_source.enabled',
  SETTINGS_UPDATED: 'settings.updated',
  ENRICHMENT_SETTINGS_UPDATED: 'enrichment.settings.updated',
  ENRICHMENT_KEY_REMOVED: 'enrichment.key.removed',
  RDAP_ENRICHMENT_REQUESTED: 'enrichment.rdap.requested',
  RDAP_ENRICHMENT_COMPLETED: 'enrichment.rdap.completed',
  RDAP_ENRICHMENT_FAILED: 'enrichment.rdap.failed',
  IP_ENRICHMENT_REQUESTED: 'enrichment.ip.requested',
  IP_ENRICHMENT_COMPLETED: 'enrichment.ip.completed',
  IP_ENRICHMENT_FAILED: 'enrichment.ip.failed',
  ABUSEIPDB_ENRICHMENT_REFRESH: 'enrichment.abuseipdb.refresh',
  IOC_ANALYST_INTELLIGENCE_CREATED: 'ioc.analyst_intelligence.created',
  IOC_ANALYST_INTELLIGENCE_UPDATED: 'ioc.analyst_intelligence.updated',
  IOC_ANALYST_INTELLIGENCE_DELETED: 'ioc.analyst_intelligence.deleted',
  VT_ENRICHMENT_REQUESTED: 'enrichment.virustotal.requested',
  VT_ENRICHMENT_COMPLETED: 'enrichment.virustotal.completed',
  VT_ENRICHMENT_NOT_INDEXED: 'enrichment.virustotal.not_indexed',
  VT_ENRICHMENT_FAILED: 'enrichment.virustotal.failed',
  ENRICHMENT_PROVIDER_CONFIG_UPDATED: 'enrichment.provider_config.updated',
  AUTH_LOGIN_SUCCESS: 'auth.login.success',
  AUTH_LOGIN_FAILED: 'auth.login.failed',
  AUTH_LOGOUT: 'auth.logout',
  CUSTOM_FEED_CREATED: 'custom_feed.created',
  CUSTOM_FEED_UPDATED: 'custom_feed.updated',
  CUSTOM_FEED_DEACTIVATED: 'custom_feed.deactivated',
  CUSTOM_FEED_SYNC_QUEUED: 'custom_feed.sync_queued',
  CUSTOM_FEED_SYNC_COMPLETED: 'custom_feed.sync_completed',
  CUSTOM_FEED_SYNC_FAILED: 'custom_feed.sync_failed'
});

export const AUDIT_ENTITY = Object.freeze({
  IOC: 'ioc',
  IOC_SUPPRESSION: 'ioc_suppression',
  IOC_MATCH_EVENT: 'ioc_match_event',
  INCIDENT: 'incident',
  USER: 'user',
  API_KEY: 'api_key',
  INTEGRATION: 'integration',
  IOC_FEED_MEMBERSHIP: 'ioc_feed_membership',
  FEED: 'feed',
  TAG: 'tag',
  THREAT_ACTOR: 'threat_actor',
  THREAT_CLASSIFICATION: 'threat_classification',
  IOC_SOURCE: 'ioc_source',
  SETTINGS: 'settings',
  ENRICHMENT: 'enrichment',
  ENVIRONMENT_AI_INSIGHT: 'environment_ai_insight',
  AUTH: 'auth',
  CUSTOM_THREAT_FEED: 'custom_threat_feed'
});

/** Human-readable labels for UI */
export const AUDIT_ACTION_LABELS = Object.freeze({
  [AUDIT_ACTION.IOC_CREATED]: 'IOC Created',
  [AUDIT_ACTION.IOC_DELETED]: 'IOC Deleted',
  [AUDIT_ACTION.IOC_TAG_ADDED]: 'IOC Tag Added',
  [AUDIT_ACTION.IOC_TAG_REMOVED]: 'IOC Tag Removed',
  [AUDIT_ACTION.IOC_SUPPRESSION_CREATED]: 'IOC Suppression Created',
  [AUDIT_ACTION.IOC_SUPPRESSION_UPDATED]: 'IOC Suppression Updated',
  [AUDIT_ACTION.IOC_SUPPRESSION_DELETED]: 'IOC Suppression Deleted',
  [AUDIT_ACTION.IOC_MATCH_EVENT_VERDICT_CHANGED]: 'Match Event Verdict Changed',
  [AUDIT_ACTION.INCIDENT_UPDATED]: 'Incident Updated',
  [AUDIT_ACTION.INCIDENT_CLOSED]: 'Incident Closed',
  [AUDIT_ACTION.INCIDENT_REOPENED]: 'Incident Reopened',
  [AUDIT_ACTION.INCIDENT_VERDICT_CHANGED]: 'Incident Verdict Changed',
  [AUDIT_ACTION.INCIDENT_ASSIGNED]: 'Incident Assigned',
  [AUDIT_ACTION.INCIDENT_AI_INSIGHT_UPDATED]: 'AI Insight Updated',
  [AUDIT_ACTION.ENVIRONMENT_AI_INSIGHT_REFRESH]: 'Environment AI Insight Refresh',
  [AUDIT_ACTION.USER_CREATED]: 'User Created',
  [AUDIT_ACTION.USER_UPDATED]: 'User Updated',
  [AUDIT_ACTION.USER_DELETED]: 'User Deleted',
  [AUDIT_ACTION.USER_ROLE_CHANGED]: 'User Role Changed',
  [AUDIT_ACTION.USER_PASSWORD_CHANGED]: 'Password Changed',
  [AUDIT_ACTION.USER_STATUS_CHANGED]: 'User Status Changed',
  [AUDIT_ACTION.API_KEY_CREATED]: 'API Key Created',
  [AUDIT_ACTION.API_KEY_UPDATED]: 'API Key Updated',
  [AUDIT_ACTION.API_KEY_ROTATED]: 'API Key Rotated',
  [AUDIT_ACTION.API_KEY_DELETED]: 'API Key Revoked',
  [AUDIT_ACTION.INTEGRATION_ENABLED]: 'Integration Enabled',
  [AUDIT_ACTION.INTEGRATION_DISABLED]: 'Integration Disabled',
  [AUDIT_ACTION.INTEGRATION_TRUST_LEVEL_CHANGED]: 'Integration Trust Level Changed',
  [AUDIT_ACTION.INTEGRATION_SCHEDULE_CHANGED]: 'Integration Schedule Changed',
  [AUDIT_ACTION.INTEGRATION_FEED_CONFIDENCE_UPDATED]: 'Feed Default Confidence Updated',
  [AUDIT_ACTION.INTEGRATION_CREDENTIALS_CHANGED]: 'Integration Credentials Changed',
  [AUDIT_ACTION.INTEGRATION_RUN_TRIGGERED]: 'Integration Run Triggered',
  [AUDIT_ACTION.INTEGRATION_QUEUE_RECOVERY]: 'Integration Queue Recovery',
  [AUDIT_ACTION.FEED_DATA_PURGE_PREVIEW]: 'Feed Data Purge Preview',
  [AUDIT_ACTION.FEED_DATA_PURGE_REQUESTED]: 'Feed Data Purge Requested',
  [AUDIT_ACTION.FEED_DATA_PURGED]: 'Feed Data Purged',
  [AUDIT_ACTION.FEED_DATA_PURGE_FAILED]: 'Feed Data Purge Failed',
  [AUDIT_ACTION.FEED_ARCHIVED]: 'Feed Archived',
  [AUDIT_ACTION.FEED_RESTORED]: 'Feed Restored',
  [AUDIT_ACTION.THREAT_FEED_EXPIRATION_POLICY_CREATED]: 'Feed Expiration Policy Created',
  [AUDIT_ACTION.THREAT_FEED_EXPIRATION_POLICY_UPDATED]: 'Feed Expiration Policy Updated',
  [AUDIT_ACTION.THREAT_FEED_EXPIRATION_POLICY_DISABLED]: 'Feed Expiration Policy Disabled',
  [AUDIT_ACTION.IOC_FEED_MEMBERSHIP_EXPIRED]: 'IOC Feed Membership Expired',
  [AUDIT_ACTION.IOC_FEED_MEMBERSHIP_REACTIVATED_BY_FEED]: 'IOC Feed Membership Reactivated (Feed)',
  [AUDIT_ACTION.IOC_FEED_MEMBERSHIP_OVERRIDE_SET]: 'IOC Feed Membership Override Set',
  [AUDIT_ACTION.IOC_FEED_MEMBERSHIP_OVERRIDE_CLEARED]: 'IOC Feed Membership Override Cleared',
  [AUDIT_ACTION.IOC_FEED_MEMBERSHIP_EXPIRED_BY_USER]: 'IOC Feed Membership Expired (User)',
  [AUDIT_ACTION.IOC_STATUS_CHANGED]: 'IOC Status Changed',
  [AUDIT_ACTION.IOC_EXPIRED]: 'IOC Expired',
  [AUDIT_ACTION.IOC_REACTIVATED_BY_USER]: 'IOC Reactivated (User)',
  [AUDIT_ACTION.IOC_OVERRIDE_SET]: 'IOC Override Set',
  [AUDIT_ACTION.IOC_OVERRIDE_CLEARED]: 'IOC Override Cleared',
  [AUDIT_ACTION.IOC_CONFIDENCE_OVERRIDE_SET]: 'IOC Confidence Override Set',
  [AUDIT_ACTION.IOC_CONFIDENCE_OVERRIDE_CLEARED]: 'IOC Confidence Override Cleared',
  [AUDIT_ACTION.FEED_CREATED]: 'Published Feed Created',
  [AUDIT_ACTION.FEED_UPDATED]: 'Published Feed Updated',
  [AUDIT_ACTION.FEED_DELETED]: 'Published Feed Deleted',
  [AUDIT_ACTION.FEED_RUN_TRIGGERED]: 'Feed Regeneration Triggered',
  [AUDIT_ACTION.FEED_ACCESS_KEY_CREATED]: 'Feed Access Key Created',
  [AUDIT_ACTION.FEED_ACCESS_KEY_UPDATED]: 'Feed Access Key Updated',
  [AUDIT_ACTION.FEED_ACCESS_KEY_REVOKED]: 'Feed Access Key Revoked',
  [AUDIT_ACTION.TAG_CREATED]: 'Tag Created',
  [AUDIT_ACTION.TAG_UPDATED]: 'Tag Updated',
  [AUDIT_ACTION.TAG_DISABLED]: 'Tag Disabled',
  [AUDIT_ACTION.TAG_ENABLED]: 'Tag Enabled',
  [AUDIT_ACTION.THREAT_ACTOR_CREATED]: 'Threat Actor Created',
  [AUDIT_ACTION.THREAT_ACTOR_UPDATED]: 'Threat Actor Updated',
  [AUDIT_ACTION.THREAT_ACTOR_DISABLED]: 'Threat Actor Disabled',
  [AUDIT_ACTION.THREAT_ACTOR_ENABLED]: 'Threat Actor Enabled',
  [AUDIT_ACTION.THREAT_CLASSIFICATION_CREATED]: 'Threat Classification Created',
  [AUDIT_ACTION.THREAT_CLASSIFICATION_UPDATED]: 'Threat Classification Updated',
  [AUDIT_ACTION.THREAT_CLASSIFICATION_DISABLED]: 'Threat Classification Disabled',
  [AUDIT_ACTION.THREAT_CLASSIFICATION_ENABLED]: 'Threat Classification Enabled',
  [AUDIT_ACTION.IOC_THREAT_CLASSIFICATION_UPDATED]: 'IOC Threat Classification Updated',
  [AUDIT_ACTION.IOC_THREAT_CLASSIFICATIONS_UPDATED]: 'IOC Threat Classifications Updated',
  [AUDIT_ACTION.IOC_THREAT_ACTOR_UPDATED]: 'IOC Threat Actor Updated',
  [AUDIT_ACTION.IOC_SOURCE_CREATED]: 'IOC Source Created',
  [AUDIT_ACTION.IOC_SOURCE_UPDATED]: 'IOC Source Updated',
  [AUDIT_ACTION.IOC_SOURCE_DISABLED]: 'IOC Source Disabled',
  [AUDIT_ACTION.IOC_SOURCE_ENABLED]: 'IOC Source Enabled',
  [AUDIT_ACTION.SETTINGS_UPDATED]: 'Settings Updated',
  [AUDIT_ACTION.ENRICHMENT_SETTINGS_UPDATED]: 'Enrichment Settings Updated',
  [AUDIT_ACTION.ENRICHMENT_KEY_REMOVED]: 'Enrichment API Key Removed',
  [AUDIT_ACTION.RDAP_ENRICHMENT_REQUESTED]: 'RDAP Enrichment Requested',
  [AUDIT_ACTION.RDAP_ENRICHMENT_COMPLETED]: 'RDAP Enrichment Completed',
  [AUDIT_ACTION.RDAP_ENRICHMENT_FAILED]: 'RDAP Enrichment Failed',
  [AUDIT_ACTION.IP_ENRICHMENT_REQUESTED]: 'IP Enrichment Requested',
  [AUDIT_ACTION.IP_ENRICHMENT_COMPLETED]: 'IP Enrichment Completed',
  [AUDIT_ACTION.IP_ENRICHMENT_FAILED]: 'IP Enrichment Failed',
  [AUDIT_ACTION.ABUSEIPDB_ENRICHMENT_REFRESH]: 'AbuseIPDB Enrichment Refresh',
  [AUDIT_ACTION.IOC_ANALYST_INTELLIGENCE_CREATED]: 'Analyst Intelligence Reference Added',
  [AUDIT_ACTION.IOC_ANALYST_INTELLIGENCE_UPDATED]: 'Analyst Intelligence Reference Updated',
  [AUDIT_ACTION.IOC_ANALYST_INTELLIGENCE_DELETED]: 'Analyst Intelligence Reference Deleted',
  [AUDIT_ACTION.VT_ENRICHMENT_REQUESTED]: 'VirusTotal Enrichment Requested',
  [AUDIT_ACTION.VT_ENRICHMENT_COMPLETED]: 'VirusTotal Enrichment Completed',
  [AUDIT_ACTION.VT_ENRICHMENT_NOT_INDEXED]: 'VirusTotal Report Not Found',
  [AUDIT_ACTION.VT_ENRICHMENT_FAILED]: 'VirusTotal Enrichment Failed',
  [AUDIT_ACTION.ENRICHMENT_PROVIDER_CONFIG_UPDATED]: 'Enrichment Provider Config Updated',
  [AUDIT_ACTION.AUTH_LOGIN_SUCCESS]: 'Login Success',
  [AUDIT_ACTION.AUTH_LOGIN_FAILED]: 'Login Failed',
  [AUDIT_ACTION.AUTH_LOGOUT]: 'Logout',
  [AUDIT_ACTION.CUSTOM_FEED_CREATED]: 'Custom Threat Feed Created',
  [AUDIT_ACTION.CUSTOM_FEED_UPDATED]: 'Custom Threat Feed Updated',
  [AUDIT_ACTION.CUSTOM_FEED_DEACTIVATED]: 'Custom Threat Feed Deactivated',
  [AUDIT_ACTION.CUSTOM_FEED_SYNC_QUEUED]: 'Custom Threat Feed Sync Queued',
  [AUDIT_ACTION.CUSTOM_FEED_SYNC_COMPLETED]: 'Custom Threat Feed Sync Completed',
  [AUDIT_ACTION.CUSTOM_FEED_SYNC_FAILED]: 'Custom Threat Feed Sync Failed'
});

export function auditActionLabel(action) {
  return AUDIT_ACTION_LABELS[action] || String(action || '').replace(/\./g, ' › ');
}
